#!/bin/bash
mkdir /mnt/branch_files
mkdir /mnt/network_files
mkdir /mnt/admin_files

chown branch_admin:branch_group /mnt/branch_files
chown network_admin:network_group /mnt/network_files
chown admin:admin_group /mnt/admin_files

chmod 750 /mnt/branch_files
chmod 750 /mnt/network_files
chmod 750 /mnt/admin_files
